
services:
  server:
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - "9005:9000"
    restart: always
    volumes:
      - ./model:/mnt/model
      - ./router:/mnt/router
      - ./util:/mnt/util
      - ./alembic:/mnt/alembic
      - ./app.py:/mnt/app.py
      - ./secret:/mnt/secret
      - ./static:/mnt/static
    environment:
      SERVICE_NAME: "hunter-server"

networks:
  default:
    driver: bridge